# Generated by Django 5.2.14 on 2026-05-19 22:58

import django.db.models.deletion
import services.encryption.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', services.encryption.fields.EncryptedDecimalField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.payperiod')),
            ],
            options={
                'verbose_name': 'bonus',
                'verbose_name_plural': 'bonuses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', services.encryption.fields.EncryptedDecimalField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.payperiod')),
            ],
            options={
                'verbose_name': 'deduction',
                'verbose_name_plural': 'deductions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseReimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', services.encryption.fields.EncryptedDecimalField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.payperiod')),
            ],
            options={
                'verbose_name': 'expense reimbursement',
                'verbose_name_plural': 'expense reimbursements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
