# Generated by Django 5.2.14 on 2026-05-18 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="DNS-safe subdomain identifier (e.g. 'acme' for acme.payroll.example.com).", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be 1-63 chars, lowercase letters/digits/hyphens, no leading or trailing hyphen.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')])),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('PK', 'Pakistan'), ('ET', 'Ethiopia')], max_length=2)),
                ('currency', models.CharField(choices=[('PKR', 'Pakistani Rupee'), ('ETB', 'Ethiopian Birr')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
