# Generated by Django 5.2.14 on 2026-06-10 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_code'),
        ('payroll', '0002_rls'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sheet', to='payroll.payperiod')),
            ],
            options={
                'verbose_name': 'attendance sheet',
                'verbose_name_plural': 'attendance sheets',
                'ordering': ['-period__year', '-period__month'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('days_late', models.PositiveSmallIntegerField(default=0)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('days_absent_without_leave', models.PositiveSmallIntegerField(default=0)),
                ('days_leave', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesheet')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ['employee__last_name', 'employee__first_name'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'employee'), name='unique_sheet_employee_attendance')],
            },
        ),
    ]
