# Generated by Django 5.2.14 on 2026-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_absent_check_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='off_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
