# Generated by Django 5.2.14 on 2026-05-19 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=16)),
                ('target_model', models.CharField(help_text="App-qualified model label, e.g. 'employees.Employee'.", max_length=200)),
                ('target_id', models.CharField(help_text='Primary key of the target row, stringified.', max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action; null for system-initiated changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='tenants.company')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['company', '-occurred_at'], name='audit_audit_company_823d79_idx'), models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__1415e4_idx')],
            },
        ),
    ]
