# Generated by Django 5.2.14 on 2026-05-19 22:57

import django.db.models.deletion
import services.encryption.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', services.encryption.fields.EncryptedDecimalField(blank=True, null=True)),
                ('units_processed', services.encryption.fields.EncryptedDecimalField(blank=True, null=True)),
                ('base_pay', services.encryption.fields.EncryptedDecimalField()),
                ('bonuses_total', services.encryption.fields.EncryptedDecimalField()),
                ('deductions_total', services.encryption.fields.EncryptedDecimalField()),
                ('reimbursements_total', services.encryption.fields.EncryptedDecimalField()),
                ('net_pay', services.encryption.fields.EncryptedDecimalField()),
                ('currency', models.CharField(max_length=3)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payperiod')),
            ],
            options={
                'ordering': ['-period__year', '-period__month', 'employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('base', 'Base pay'), ('bonus', 'Bonus'), ('deduction', 'Deduction'), ('reimbursement', 'Reimbursement')], max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('amount', services.encryption.fields.EncryptedDecimalField()),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
            ],
            options={
                'ordering': ['line_type', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payperiod',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_company_period'),
        ),
        migrations.AddConstraint(
            model_name='payperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='period_month_1_to_12'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('employee', 'period'), name='unique_employee_period'),
        ),
    ]
