# Generated by Django 5.2.14 on 2026-06-16 05:28

import services.encryption.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_rls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='hours_worked',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='units_processed',
        ),
        migrations.AddField(
            model_name='payslip',
            name='allowances_total',
            field=services.encryption.fields.EncryptedDecimalField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslipline',
            name='line_type',
            field=models.CharField(choices=[('base', 'Base pay'), ('allowance', 'Allowance'), ('bonus', 'Bonus'), ('deduction', 'Deduction'), ('reimbursement', 'Reimbursement')], max_length=16),
        ),
    ]
