# Generated by Django 5.2.14 on 2026-05-19 22:38

import django.db.models.deletion
import services.encryption.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('national_id', services.encryption.fields.EncryptedTextField(blank=True, null=True)),
                ('passport_number', services.encryption.fields.EncryptedTextField(blank=True, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('visa_number', services.encryption.fields.EncryptedTextField(blank=True, null=True)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('bank_account_number', services.encryption.fields.EncryptedTextField(blank=True, null=True)),
                ('pay_basis', models.CharField(choices=[('fixed', 'Fixed monthly salary'), ('hourly', 'Hourly'), ('unit', 'Unit-based')], max_length=16)),
                ('base_salary', services.encryption.fields.EncryptedDecimalField(blank=True, null=True)),
                ('hourly_rate', services.encryption.fields.EncryptedDecimalField(blank=True, null=True)),
                ('unit_rate', services.encryption.fields.EncryptedDecimalField(blank=True, null=True)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
