# Generated by Django 5.2.14 on 2026-06-16 05:28

import services.encryption.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pay_basis',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='unit_rate',
        ),
        migrations.AddField(
            model_name='employee',
            name='attendance_allowance',
            field=services.encryption.fields.EncryptedDecimalField(blank=True, default=Decimal('0')),
        ),
        migrations.AddField(
            model_name='employee',
            name='conveyance_allowance',
            field=services.encryption.fields.EncryptedDecimalField(blank=True, default=Decimal('0')),
        ),
        migrations.AddField(
            model_name='employee',
            name='performance_bonus',
            field=services.encryption.fields.EncryptedDecimalField(blank=True, default=Decimal('0')),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=services.encryption.fields.EncryptedDecimalField(default=0),
            preserve_default=False,
        ),
    ]
